export const VOUCHER_WHERE_TYPE = {
  WHERE_TYPE_TICKET: 1,
  WHERE_TYPE_CASH: 2, 
};

export const VOUCHER_MONEY_TYPE = {
  MONEY_TYPE_AMOUNT: 1,
  MONEY_TYPE_DISCOUNT: 2,
};

export const VOUCHER_BONUS_TYPE = {
  BONUS_TYPE_BONUS: 1,
  BONUS_TYPE_CASH: 2,
};

export const VOUCHER_LOTTERY_TYPE = {
  LOTTERY_ALL: 1,
  LOTTERY_SPECIFIC: 2,
};

export const VOUCHER_DATE_STATUS = {
  DATE_STATUS_PENDING: 0,
  DATE_STATUS_ACTIVE: 1,
  DATE_STATUS_EXPIRED: 2,
};

export const VOUCHER_REDEEM_STATUS = {
  REDEEM_STATUS_FREE: 0,
  REDEEM_STATUS_USE: 1,
  REDEEM_STATUS_UNAVAILABLE: 2,
};

export const VOUCHER_USER = {
  STATUS_REDEEM: 0,
  STATUS_USED: 1,
  STATUS_EXPIRED: 2,
};
