export const USER_ROLE = {
  ROLE_USER: 10,
  ROLE_ADMIN: 20,
};

export const USER_FROM_WHERE = {
  FROM_WEBSITE: 0,
  FROM_MOBILE: 1,
  FROM_AGENT: 2,
  FROM_ADMIN: 3,
};

export const USER_TYPE = {
  TYPE_USER: 10,
  TYPE_REFERRAL: 20,
  TYPE_AGENT: 30,
  TYPE_INFLUENCE: 40,
};

export const USER_STATUS = {
  STATUS_DELETED: 0,
  STATUS_ACTIVE: 10,
  STATUS_BANNED: 20,
  STATUS_SELF_EXCLUSION: 30,
};

export const USER_GENDER = {
  GENDER_MALE: 10,
  GENDER_FEMALE: 20,
};

export const USER_NOTIFICATIONS = {
  NOTIFICATIONS_ALL: 0,
  NOTIFICATIONS_SOME: 1,
};

export const USER_TIMEZONE = {
  TIMEZONE_APPROVED: 10,
  TIMEZONE_DISAPPROVED: 20,
  TIMEZONE_UNCHECKED: 0,
};


